// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01oIc-vdm9R2TdDviVmUXJEARNNiPy9Y',
    appId: '1:671527744126:web:98ba01fe8f3aa3d384de2f',
    messagingSenderId: '671527744126',
    projectId: 'alu-spark-726ef',
    authDomain: 'alu-spark-726ef.firebaseapp.com',
    storageBucket: 'alu-spark-726ef.firebasestorage.app',
    measurementId: 'G-WT7WKQ2VX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUmsDW5KwudJLrevcHwaTxtLxRaN-2SlA',
    appId: '1:671527744126:android:c11b262de4f34b7484de2f',
    messagingSenderId: '671527744126',
    projectId: 'alu-spark-726ef',
    storageBucket: 'alu-spark-726ef.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbg4f7l1__LsYxhbXd_916_eICz_UovRg',
    appId: '1:671527744126:ios:88a7e1432390980f84de2f',
    messagingSenderId: '671527744126',
    projectId: 'alu-spark-726ef',
    storageBucket: 'alu-spark-726ef.firebasestorage.app',
    iosClientId: '671527744126-qvili98g15614o6pnq49lojjuk0gbedo.apps.googleusercontent.com',
    iosBundleId: 'com.example.aluSpark',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbg4f7l1__LsYxhbXd_916_eICz_UovRg',
    appId: '1:671527744126:ios:88a7e1432390980f84de2f',
    messagingSenderId: '671527744126',
    projectId: 'alu-spark-726ef',
    storageBucket: 'alu-spark-726ef.firebasestorage.app',
    iosClientId: '671527744126-qvili98g15614o6pnq49lojjuk0gbedo.apps.googleusercontent.com',
    iosBundleId: 'com.example.aluSpark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC01oIc-vdm9R2TdDviVmUXJEARNNiPy9Y',
    appId: '1:671527744126:web:5fe401698e6d200a84de2f',
    messagingSenderId: '671527744126',
    projectId: 'alu-spark-726ef',
    authDomain: 'alu-spark-726ef.firebaseapp.com',
    storageBucket: 'alu-spark-726ef.firebasestorage.app',
    measurementId: 'G-M7DVEJJW5Y',
  );
}
